AWSTemplateFormatVersion: '2010-09-09'
Description: IAM roles for CodeBuild
Resources:
  CodeBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
                - events.amazonaws.com
        Version: 2012-10-17
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - 'iam:PassRole'
                  - 'iam:GetRole'
                  - 'iam:CreateRole'
                  - 'iam:PutRolePolicy'
                  - 'iam:DeleteRolePolicy'
                  - 'iam:DeleteRole'
                  - 'iam:AttachRolePolicy'
                  - 'events:*'
                  - 'cloudformation:*'
                  - 'lambda:*'
                  - 'apigateway:*'
                  - 's3:*'
                  - 'logs:*'
                  - 'dynamodb:*'
                  - 'sqs:*'
                  - 'application-autoscaling:*'
                  - 'ec2:*' # vpc required this
                  - 'cloudfront:CreateInvalidation' # to flush CDN after deployment
                Effect: Allow
                Resource: '*'
            Version: 2012-10-17
          PolicyName: abo-events-code-build-policy
      RoleName: abo-events-code-build-role
      Tags:
        - Key: 'ApplicationID'
          Value: 'APP3151073'
        - Key: 'Environment'
          Value: 'QA' # update this to PROD on PROD env
